import { mkdir, readFile, writeFile } from 'node:fs/promises';

const keys = ['mascot', 'coin', 'trophy', 'classic-art', 'time-art'];
const entries = await Promise.all(keys.map(async (key) => {
  const xml = await readFile(new URL(`../assets/art/${key}.svg`, import.meta.url), 'utf8');
  if (!xml.startsWith('<svg') || !xml.trimEnd().endsWith('</svg>')) {
    throw new Error(`Invalid SVG artwork: ${key}`);
  }
  return [key, xml];
}));

const output = new URL('../src/ui/artwork.ts', import.meta.url);
await mkdir(new URL('.', output), { recursive: true });
await writeFile(output, '// Generated by scripts/embed-artwork.mjs. Do not edit by hand.\n' +
  `export const ART = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const;\n`);
console.log(`Embedded ${entries.length} original SVGs in src/ui/artwork.ts`);
