import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
if (args.some((arg) => arg.startsWith('--') && arg !== '--fetch-fonts')) {
  throw new Error('Usage: node scripts/extract-assets.mjs [source.html] [--fetch-fonts]');
}
const source = resolve(args.find((arg) => !arg.startsWith('--')) ?? resolve(root, '../outputs/app-name-ui.html'));
const html = await readFile(source, 'utf8');
const artDir = resolve(root, 'assets/art');
const fontDir = resolve(root, 'assets/fonts');
const sha256 = (data) => createHash('sha256').update(data).digest('hex');
const files = [];

async function save(path, data, origin) {
  await writeFile(path, data);
  const bytes = Buffer.byteLength(data);
  files.push({ file: relative(root, path), bytes, sha256: sha256(data), source: origin });
  console.log(`${relative(root, path)}: ${bytes} bytes`);
}

await mkdir(artDir, { recursive: true });
for (const name of ['mascot', 'classic-art', 'time-art', 'trophy', 'coin']) {
  const matches = [...html.matchAll(/<symbol\b([^>]*)>([\s\S]*?)<\/symbol\s*>/g)]
    .filter((match) => match[1].match(/\bid\s*=\s*(["'])(.*?)\1/)?.[2] === name);
  if (matches.length !== 1) throw new Error(`Expected exactly one symbol #${name}`);
  const [, attributes, content] = matches[0];
  const viewBox = attributes.match(/\bviewBox\s*=\s*(["'])(.*?)\1/)?.[2];
  const dimensions = viewBox?.trim().split(/\s+/).map(Number);
  if (dimensions?.length !== 4 || !dimensions.every(Number.isFinite) || dimensions[2] <= 0 || dimensions[3] <= 0) {
    throw new Error(`Invalid viewBox for #${name}`);
  }
  const ids = new Set([...content.matchAll(/\bid\s*=\s*["']([^"']+)["']/g)].map((match) => match[1]));
  for (const match of content.matchAll(/url\(\s*["']?#([^\s)"']+)["']?\s*\)|(?:href|xlink:href)\s*=\s*["']#([^"']+)/g)) {
    if (!ids.has(match[1] ?? match[2])) throw new Error(`Unresolved SVG reference in #${name}: ${match[0]}`);
  }
  // Keep the complete symbol body verbatim, including nested defs and gradients.
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${dimensions[2]}" height="${dimensions[3]}"${attributes.replace(/\s+id\s*=\s*(["']).*?\1/, '')}>${content}</svg>\n`;
  await save(resolve(artDir, `${name}.svg`), svg, `${relative(root, source)}#${name}`);
}

const fonts = [
  {
    file: 'Nunito-Bold.ttf', family: 'Nunito', weight: 700,
    url: 'https://fonts.gstatic.com/s/nunito/v32/XRXI3I6Li01BKofiOc5wtlZ2di8HDFwmRTM.ttf',
  },
  {
    file: 'Nunito-ExtraBold.ttf', family: 'Nunito', weight: 800,
    url: 'https://fonts.gstatic.com/s/nunito/v32/XRXI3I6Li01BKofiOc5wtlZ2di8HDDsmRTM.ttf',
  },
  {
    file: 'TitanOne-Regular.ttf', family: 'Titan One', weight: 400,
    url: 'https://fonts.gstatic.com/s/titanone/v17/mFTzWbsGxbbS_J5cQcjykw.ttf',
  },
];
const licenses = [
  { file: 'OFL-Nunito.txt', url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/nunito/OFL.txt' },
  { file: 'OFL-TitanOne.txt', url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/titanone/OFL.txt' },
];

await mkdir(fontDir, { recursive: true });
let css = '/* Generated by scripts/extract-assets.mjs. SIL OFL 1.1; see OFL-*.txt. No remote font requests. */\n';
for (const item of [...fonts, ...licenses]) {
  const path = resolve(fontDir, item.file);
  let data;
  if (args.includes('--fetch-fonts')) {
    const response = await fetch(item.url, { signal: AbortSignal.timeout(30_000) });
    if (!response.ok) throw new Error(`${response.status}: ${item.url}`);
    data = Buffer.from(await response.arrayBuffer());
  } else {
    try {
      data = await readFile(path);
    } catch {
      throw new Error(`Missing ${item.file}. Run once with --fetch-fonts, then regeneration is offline.`);
    }
  }
  if (item.file.endsWith('.ttf')) {
    if (data.length < 1024 || data.readUInt32BE(0) !== 0x00010000) throw new Error(`Invalid TTF: ${item.file}`);
    css += `@font-face{font-family:'${item.family}';font-style:normal;font-weight:${item.weight};font-display:swap;src:url(data:font/ttf;base64,${data.toString('base64')}) format('truetype')}\n`;
  } else if (!data.toString('utf8').includes('SIL OPEN FONT LICENSE Version 1.1')) {
    throw new Error(`Invalid OFL license: ${item.file}`);
  }
  await save(path, data, item.url);
}
await save(resolve(fontDir, 'fonts.css'), css, 'Embedded, unmodified TTFs listed above');
await writeFile(resolve(root, 'assets/graphics-fonts-manifest.json'), `${JSON.stringify({
  generator: 'scripts/extract-assets.mjs',
  source: relative(root, source),
  sourceSha256: sha256(html),
  fontCssSource: 'https://fonts.googleapis.com/css2?family=Nunito:wght@700;800&family=Titan+One&display=swap',
  files,
}, null, 2)}\n`);
